deb:
	g++-7 -std=c++11 -I ../../../source/ -DSFLOATTYPE=double -g container_test.cpp -o container_test.bin 2>results_make.txt
rel:
	g++-7 -std=c++11 -I ../../../source/ -DSFLOATTYPE=double -O3 container_test.cpp -o container_test.bin 2>results_make.txt	