# deb:
# 	g++-7 -std=c++11 -I ../../../source/ -DSFLOATTYPE=double -g container_test.cpp -o container_test.bin 2>results_make.txt
# rel:
# 	g++-7 -std=c++11 -I ../../../source/ -DSFLOATTYPE=double -O3 container_test.cpp -o container_test.bin 2>results_make.txt	
deb:
	g++ -std=c++11 -DSFLOATTYPE=double -g curve_container.cpp -o curve_container.cpp.bin 2>results_make.txt
rel:
	g++ -std=c++11 -DSFLOATTYPE=double -O3 curve_container.cpp -o curve_container.cpp.bin 2>results_make.txt